<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Introduction" data-toc-modified-id="Introduction-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Introduction</a></span></li><li><span><a href="#Objectives" data-toc-modified-id="Objectives-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Objectives</a></span></li><li><span><a href="#Instructions" data-toc-modified-id="Instructions-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Instructions</a></span></li><li><span><a href="#Distributive-Property---Matrices-multiplication-is-distributive" data-toc-modified-id="Distributive-Property---Matrices-multiplication-is-distributive-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Distributive Property - Matrices multiplication is distributive</a></span><ul class="toc-item"><li><span><a href="#Prove-that-A.(B+C)=A.B+A.C" data-toc-modified-id="Prove-that-A.(B+C)=A.B+A.C-4.1"><span class="toc-item-num">4.1&nbsp;&nbsp;</span>Prove that A.(B+C)=A.B+A.C</a></span></li></ul></li><li><span><a href="#Associative-Property---Matrices-multiplication-is-associative" data-toc-modified-id="Associative-Property---Matrices-multiplication-is-associative-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Associative Property - Matrices multiplication is associative</a></span><ul class="toc-item"><li><span><a href="#Prove-that-A.(B.C)=(A.B).C" data-toc-modified-id="Prove-that-A.(B.C)=(A.B).C-5.1"><span class="toc-item-num">5.1&nbsp;&nbsp;</span>Prove that A.(B.C)=(A.B).C</a></span></li></ul></li><li><span><a href="#Commutative-Property---Matrix-multiplication-is-NOT-commutative" data-toc-modified-id="Commutative-Property---Matrix-multiplication-is-NOT-commutative-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>Commutative Property - Matrix multiplication is NOT commutative</a></span><ul class="toc-item"><li><span><a href="#Prove-that-for-matrices,-A.B-≠-B.A" data-toc-modified-id="Prove-that-for-matrices,-A.B-≠-B.A-6.1"><span class="toc-item-num">6.1&nbsp;&nbsp;</span>Prove that for matrices, A.B ≠ B.A</a></span></li></ul></li><li><span><a href="#Commutative-Property----vector-multiplication-IS-commutative" data-toc-modified-id="Commutative-Property----vector-multiplication-IS-commutative-7"><span class="toc-item-num">7&nbsp;&nbsp;</span>Commutative Property -  vector multiplication IS commutative</a></span><ul class="toc-item"><li><span><a href="#Prove-that-for-vectors,-xT-.-y-=-yT-.-x" data-toc-modified-id="Prove-that-for-vectors,-xT-.-y-=-yT-.-x-7.1"><span class="toc-item-num">7.1&nbsp;&nbsp;</span>Prove that for vectors, x<sup>T</sup> . y = y<sup>T</sup> . x</a></span><ul class="toc-item"><li><span><a href="#and-finally" data-toc-modified-id="and-finally-7.1.1"><span class="toc-item-num">7.1.1&nbsp;&nbsp;</span>and finally</a></span></li></ul></li></ul></li><li><span><a href="#Simplification-of-the-matrix-product" data-toc-modified-id="Simplification-of-the-matrix-product-8"><span class="toc-item-num">8&nbsp;&nbsp;</span>Simplification of the matrix product</a></span><ul class="toc-item"><li><span><a href="#Prove-that--(A.B)T-=-BT-.-AT" data-toc-modified-id="Prove-that--(A.B)T-=-BT-.-AT-8.1"><span class="toc-item-num">8.1&nbsp;&nbsp;</span>Prove that  (A.B)<sup>T</sup> = B<sup>T</sup> . A<sup>T</sup></a></span></li></ul></li><li><span><a href="#Summary" data-toc-modified-id="Summary-9"><span class="toc-item-num">9&nbsp;&nbsp;</span>Summary</a></span></li></ul></div>

# Properties of Dot Product - Lab

## Introduction

In this lab we shall look at some interesting properties of a Dot product type matrix multiplication. Understanding these properties will become useful as we move forward with machine learning advanced linear algebra. The lab will require you to calculate results to provide a proof for these properties.

## Objectives
You will be able to:
* Understand and analytically explain Distributive, Commutative and Associative properties of dot product

## Instructions

* For each property, create suitably sized matrices with random data and prove the equations 
* Ensure that size/dimension assumptions are met while performing calculations (you'll see errors otherwise)
* Calculate the LHS and RHS for all equations and show if they are equal or not

## Distributive Property - Matrices multiplication is distributive
### Prove that A.(B+C)=A.B+A.C

In [35]:
# Your code here
import numpy as np
A = np.zeros(shape=(3,3),dtype=int)
B = np.zeros(shape=(3,3),dtype=int)
C = np.zeros(shape=(3,3),dtype=int)
for matrix in (A,B,C):
    for row in range(len(matrix)):
        for el in range(len(matrix[row])):
            matrix[row, el] = np.random.randint(0, 9)
        
D1 = A.dot(B+C)
D2 = A.dot(B)+A.dot(C)
display(D1)
display(D2)
D1 == D2

array([[ 84,  62,  98],
       [ 15,  18,  28],
       [102,  54,  89]])

array([[ 84,  62,  98],
       [ 15,  18,  28],
       [102,  54,  89]])

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

## Associative Property - Matrices multiplication is associative
### Prove that A.(B.C)=(A.B).C

In [38]:
# Your code here 
D1 = A.dot(B.dot(C))
D2 = (A.dot(B)).dot(C)
D3 = A.dot(B).dot(C)
display(D1)
display(D2)

D1 == D2

array([[330, 518, 378],
       [ 61, 161,  77],
       [398, 448, 436]])

array([[330, 518, 378],
       [ 61, 161,  77],
       [398, 448, 436]])

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

## Commutative Property - Matrix multiplication is NOT commutative
### Prove that for matrices, A.B ≠ B.A

In [39]:
# Your code here 
D1 = A.dot(B)
D2 = B.dot(A)
D1 == D2

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

## Commutative Property -  vector multiplication IS commutative
### Prove that for vectors, x<sup>T</sup> . y = y<sup>T</sup> . x
Note: superscipt<sup>T</sup> denotes the transpose we saw earlier

In [48]:
# Your code here 
v1 = A[0]
v2 = A[1]
v1.T.dot(v2) == v2.T.dot(v1)


True

#### and finally 
## Simplification of the matrix product
### Prove that  (A.B)<sup>T</sup> = B<sup>T</sup> . A<sup>T</sup>

In [49]:
# Your code here 
D1 = (A.dot(B)).T
D2 = (B.T).dot(A.T)
display(D1)
display(D2)
D1==D2

array([[60, 11, 73],
       [34,  4, 47],
       [74, 23, 64]])

array([[60, 11, 73],
       [34,  4, 47],
       [74, 23, 64]])

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

## Summary 

So now we have seen enough matrix algebra to help us solve a problem of linear equations as we saw earlier in this section. We shall see how to do this next. 